# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 12:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import imports.validators


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0002_add_shapefileimport_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shapefileimport",
            name="shapefiles",
            field=models.FileField(
                help_text="Zipped shapefiles that contains .shp, .shx and .dbf files with a common filename prefix",
                upload_to="shapefiles/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["zip"]
                    ),
                    imports.validators.ZippedShapefilesValidator(),
                ],
                verbose_name="shapefiles",
            ),
        ),
    ]
