# Generated by Django 2.0 on 2018-11-09 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0003_add_shapefile_import_upload_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shapefileimport",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
    ]
