# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='protection_level',
            field=models.IntegerField(choices=[(1, 'Administrators only'), (2, 'Administrators and staff'), (3, 'Public')], db_column='suojaustasoid'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='protection_level',
            field=models.IntegerField(choices=[(1, 'Administrators only'), (2, 'Administrators and staff'), (3, 'Public')], db_column='suojaustasoid'),
        ),
        migrations.AlterField(
            model_name='featurelink',
            name='protection_level',
            field=models.IntegerField(choices=[(1, 'Administrators only'), (2, 'Administrators and staff'), (3, 'Public')], db_column='suojaustasoid'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='protection_level',
            field=models.IntegerField(choices=[(1, 'Administrators only'), (2, 'Administrators and staff'), (3, 'Public')], db_column='suojaustasoid'),
        ),
        migrations.AlterField(
            model_name='species',
            name='protection_level',
            field=models.IntegerField(choices=[(1, 'Administrators only'), (2, 'Administrators and staff'), (3, 'Public')], db_column='suojaustasoid'),
        ),
    ]
