# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('Tile', 'Square'),
        migrations.AlterField('Square', 'id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='square', serialize=False, to='nature.Feature'))
    ]
