# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0002_protection_level_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='created_time',
            field=models.DateField(auto_now_add=True, db_column='digipvm', null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, db_column='pvm_editoitu', null=True),
        ),
        migrations.AlterField(
            model_name='habitattypeobservation',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_column='pvm_luotu'),
        ),
        migrations.AlterField(
            model_name='habitattypeobservation',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, db_column='pvm_editoitu', null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_column='pvm_luotu'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, db_column='pvm_editoitu', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_column='lisaysaika', null=True),
        ),
    ]
