# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nature", "0002_observation_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureclass",
            name="open_data",
            field=models.BooleanField(db_column="avoin_data", default=False),
        ),
    ]
