# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0002_rename_tile'),
    ]

    operations = [
        migrations.RenameModel('Incidence', 'Frequency'),
        migrations.RenameModel('BreedingCategory', 'BreedingDegree')
    ]
