# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 14:07
# This data migration was created to set the open_data field
# of features based on a set of pre-defined feature classes
# that can be published as open data. However, the list of
# open feature classes are changing over the time, and we
# cannot rely on a fixed set of feature classes to determine
# weather a feature is open data or not. Thus we cleaned up
# the migration and makes it a noop migration.
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nature", "0003_featureclass_open_data"),
    ]

    operations = []
