# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nature", "0004_open_feature_classes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featurelink",
            name="link_text",
            field=models.CharField(
                blank=True, db_column="linkin_teksti", max_length=100, null=True
            ),
        ),
    ]
