# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import nature.models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0006_alter_historical_feature_text_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abundance',
            options={'ordering': ['id'], 'verbose_name': 'abundance', 'verbose_name_plural': 'abundance'},
        ),
        migrations.AlterModelOptions(
            name='breedingdegree',
            options={'ordering': ['id'], 'verbose_name': 'breeding degree', 'verbose_name_plural': 'breeding degrees'},
        ),
        migrations.AlterModelOptions(
            name='conservationprogramme',
            options={'ordering': ['id'], 'verbose_name': 'conservation programme', 'verbose_name_plural': 'conservation programmes'},
        ),
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['id'], 'verbose_name': 'criterion', 'verbose_name_plural': 'criteria'},
        ),
        migrations.AlterModelOptions(
            name='featurelink',
            options={'ordering': ['id'], 'verbose_name': 'feature link', 'verbose_name_plural': 'feature links'},
        ),
        migrations.AlterModelOptions(
            name='featurepublication',
            options={'verbose_name': 'feature publication', 'verbose_name_plural': 'feature publications'},
        ),
        migrations.AlterModelOptions(
            name='featurevalue',
            options={'verbose_name': 'feature value', 'verbose_name_plural': 'features values'},
        ),
        migrations.AlterModelOptions(
            name='frequency',
            options={'ordering': ['id'], 'verbose_name': 'frequency', 'verbose_name_plural': 'frequencies'},
        ),
        migrations.AlterModelOptions(
            name='habitattype',
            options={'ordering': ['id'], 'verbose_name': 'habitat type', 'verbose_name_plural': 'habitat types'},
        ),
        migrations.AlterModelOptions(
            name='habitattypeobservation',
            options={'ordering': ['id'], 'verbose_name': 'habitat type observation', 'verbose_name_plural': 'habitat type observations'},
        ),
        migrations.AlterModelOptions(
            name='habitattyperegulation',
            options={'verbose_name': 'habitat type regulation', 'verbose_name_plural': 'habitat type regulations'},
        ),
        migrations.AlterModelOptions(
            name='historicalfeature',
            options={'ordering': ['id'], 'verbose_name': 'historical feature', 'verbose_name_plural': 'historical features'},
        ),
        migrations.AlterModelOptions(
            name='migrationclass',
            options={'ordering': ['id'], 'verbose_name': 'migration class', 'verbose_name_plural': 'migration class'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['id'], 'verbose_name': 'observation', 'verbose_name_plural': 'observations'},
        ),
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ['id'], 'verbose_name': 'occurrence', 'verbose_name_plural': 'occurrences'},
        ),
        migrations.AlterModelOptions(
            name='origin',
            options={'ordering': ['id'], 'verbose_name': 'origin', 'verbose_name_plural': 'origins'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id'], 'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
        migrations.AlterModelOptions(
            name='protection',
            options={'ordering': ['id'], 'verbose_name': 'protection', 'verbose_name_plural': 'protections'},
        ),
        migrations.AlterModelOptions(
            name='protectionconservationprogramme',
            options={'verbose_name': 'protection conservation programme', 'verbose_name_plural': 'protection conservation programmes'},
        ),
        migrations.AlterModelOptions(
            name='protectioncriterion',
            options={'verbose_name': 'protection criterion', 'verbose_name_plural': 'protection criteria'},
        ),
        migrations.AlterModelOptions(
            name='protectionlevel',
            options={'ordering': ['id'], 'verbose_name': 'protection level', 'verbose_name_plural': 'protection levels'},
        ),
        migrations.AlterModelOptions(
            name='publicationtype',
            options={'ordering': ['id'], 'verbose_name': 'publication type', 'verbose_name_plural': 'publication types'},
        ),
        migrations.AlterModelOptions(
            name='regulation',
            options={'ordering': ['id'], 'verbose_name': 'regulation', 'verbose_name_plural': 'regulations'},
        ),
        migrations.AlterModelOptions(
            name='speciesregulation',
            options={'verbose_name': 'species regulation', 'verbose_name_plural': 'species regulations'},
        ),
        migrations.AlterModelOptions(
            name='square',
            options={'ordering': ['id'], 'verbose_name': 'square', 'verbose_name_plural': 'squares'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['id'], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
        migrations.AlterModelOptions(
            name='transactionfeature',
            options={'verbose_name': 'transaction feature', 'verbose_name_plural': 'transaction features'},
        ),
        migrations.AlterModelOptions(
            name='transactionregulation',
            options={'verbose_name': 'transaction regulation', 'verbose_name_plural': 'transaction regulations'},
        ),
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'ordering': ['id'], 'verbose_name': 'transaction type', 'verbose_name_plural': 'transaction types'},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['id'], 'verbose_name': 'value', 'verbose_name_plural': 'values'},
        ),
        migrations.AlterField(
            model_name='abundance',
            name='explanation',
            field=models.CharField(blank=True, db_column='selitys', max_length=50, null=True, verbose_name='explanation'),
        ),
        migrations.AlterField(
            model_name='abundance',
            name='source',
            field=models.CharField(blank=True, db_column='lahde', max_length=50, null=True, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='abundance',
            name='value',
            field=models.CharField(blank=True, db_column='arvo', max_length=5, null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='breedingdegree',
            name='explanation',
            field=models.CharField(blank=True, db_column='selitys', max_length=50, null=True, verbose_name='explanation'),
        ),
        migrations.AlterField(
            model_name='breedingdegree',
            name='source',
            field=models.CharField(blank=True, db_column='lahde', max_length=50, null=True, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='breedingdegree',
            name='value',
            field=models.CharField(blank=True, db_column='arvo', max_length=50, null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='conservationprogramme',
            name='name',
            field=models.CharField(blank=True, db_column='nimi', max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='criterion',
            field=models.CharField(blank=True, db_column='peruste', max_length=50, null=True, verbose_name='criterion'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='specific_criterion',
            field=models.CharField(blank=True, db_column='tarkperuste', max_length=50, null=True, verbose_name='specific criterion'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='subcriterion',
            field=models.CharField(blank=True, db_column='alaperuste', max_length=50, null=True, verbose_name='subscriterion'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='active',
            field=models.BooleanField(db_column='voimassa', default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='area',
            field=models.FloatField(blank=True, db_column='pinta_ala', editable=False, null=True, verbose_name='area (ha)'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='created_by',
            field=models.CharField(blank=True, db_column='digitoija', max_length=50, null=True, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='created_time',
            field=models.DateField(auto_now_add=True, db_column='digipvm', null=True, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.CharField(blank=True, db_column='kuvaus', max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_class',
            field=models.ForeignKey(db_column='luokkatunnus', on_delete=django.db.models.deletion.PROTECT, related_name='features', to='nature.FeatureClass', verbose_name='feature class'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='fid',
            field=models.CharField(blank=True, db_column='tunnus', max_length=10, null=True, verbose_name='fid'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='geometry',
            field=nature.models.PermissiveGeometryField(db_column='geometry1', srid=3879, verbose_name='geometry'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='last_modified_by',
            field=models.CharField(blank=True, db_column='muokkaaja', max_length=10, null=True, verbose_name='last modified by'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, db_column='pvm_editoitu', null=True, verbose_name='last modified time'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(blank=True, db_column='nimi', max_length=80, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='notes',
            field=models.CharField(blank=True, db_column='huom', max_length=255, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='number',
            field=models.IntegerField(blank=True, db_column='numero', null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='protection_level',
            field=models.IntegerField(choices=[(1, 'Administrators only'), (2, 'Administrators and staff'), (3, 'Public')], db_column='suojaustasoid', default=3, verbose_name='protection level'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='publications',
            field=models.ManyToManyField(related_name='features', through='nature.FeaturePublication', to='nature.Publication', verbose_name='publications'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='text',
            field=models.CharField(blank=True, db_column='teksti', max_length=40000, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='text_www',
            field=models.CharField(blank=True, db_column='teksti_www', max_length=40000, null=True, verbose_name='text www'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='values',
            field=models.ManyToManyField(related_name='features', through='nature.FeatureValue', to='nature.Value', verbose_name='values'),
        ),
        migrations.AlterField(
            model_name='featureclass',
            name='additional_info',
            field=models.CharField(blank=True, db_column='lisatieto', max_length=255, null=True, verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='featureclass',
            name='id',
            field=models.CharField(db_column='tunnus', max_length=10, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='featureclass',
            name='metadata',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='featureclass',
            name='name',
            field=models.CharField(blank=True, db_column='nimi', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='featureclass',
            name='open_data',
            field=models.BooleanField(db_column='avoin_data', default=False, verbose_name='open data'),
        ),
        migrations.AlterField(
            model_name='featureclass',
            name='reporting',
            field=models.BooleanField(db_column='raportointi', default=True, verbose_name='reporting'),
        ),
        migrations.AlterField(
            model_name='featureclass',
            name='super_class',
            field=models.ForeignKey(blank=True, db_column='paatunnus', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subclasses', to='nature.FeatureClass', verbose_name='super class'),
        ),
        migrations.AlterField(
            model_name='featureclass',
            name='www',
            field=models.BooleanField(default=True, verbose_name='www'),
        ),
        migrations.AlterField(
            model_name='featurelink',
            name='feature',
            field=models.ForeignKey(db_column='tekstiid', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='nature.Feature', verbose_name='feature'),
        ),
        migrations.AlterField(
            model_name='featurelink',
            name='link',
            field=models.CharField(blank=True, db_column='linkki', max_length=4000, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='featurelink',
            name='link_text',
            field=models.CharField(blank=True, db_column='linkin_teksti', max_length=100, null=True, verbose_name='link text'),
        ),
        migrations.AlterField(
            model_name='featurelink',
            name='link_type',
            field=models.ForeignKey(db_column='tyyppiid', on_delete=django.db.models.deletion.PROTECT, to='nature.LinkType', verbose_name='link type'),
        ),
        migrations.AlterField(
            model_name='featurelink',
            name='ordering',
            field=models.IntegerField(blank=True, db_column='jarjestys', null=True, verbose_name='ordering'),
        ),
        migrations.AlterField(
            model_name='featurelink',
            name='protection_level',
            field=models.IntegerField(choices=[(1, 'Administrators only'), (2, 'Administrators and staff'), (3, 'Public')], db_column='suojaustasoid', default=3, verbose_name='protection level'),
        ),
        migrations.AlterField(
            model_name='featurelink',
            name='text',
            field=models.CharField(blank=True, db_column='linkkiteksti', max_length=4000, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='featurepublication',
            name='feature',
            field=models.ForeignKey(db_column='kohdeid', on_delete=django.db.models.deletion.CASCADE, to='nature.Feature', verbose_name='feature'),
        ),
        migrations.AlterField(
            model_name='featurepublication',
            name='publication',
            field=models.ForeignKey(db_column='julkid', on_delete=django.db.models.deletion.CASCADE, to='nature.Publication', verbose_name='publication'),
        ),
        migrations.AlterField(
            model_name='featurevalue',
            name='feature',
            field=models.ForeignKey(db_column='kohdeid', on_delete=django.db.models.deletion.CASCADE, to='nature.Feature', verbose_name='feature'),
        ),
        migrations.AlterField(
            model_name='featurevalue',
            name='value',
            field=models.ForeignKey(db_column='arvoid', on_delete=django.db.models.deletion.CASCADE, to='nature.Value', verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='explanation',
            field=models.CharField(blank=True, db_column='selitys', max_length=50, null=True, verbose_name='explanation'),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='source',
            field=models.CharField(blank=True, db_column='lahde', max_length=50, null=True, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='value',
            field=models.CharField(blank=True, db_column='arvo', max_length=5, null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='habitattype',
            name='additional_info',
            field=models.CharField(blank=True, db_column='lisatieto', max_length=255, null=True, verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='habitattype',
            name='code',
            field=models.CharField(blank=True, db_column='koodi', max_length=10, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='habitattype',
            name='description',
            field=models.CharField(blank=True, db_column='kuvaus', max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='habitattype',
            name='group',
            field=models.CharField(blank=True, db_column='ltyyppiryhma', max_length=50, null=True, verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='habitattype',
            name='name',
            field=models.CharField(blank=True, db_column='nimi', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='habitattype',
            name='regulations',
            field=models.ManyToManyField(related_name='habitat_types', through='nature.HabitatTypeRegulation', to='nature.Regulation', verbose_name='regulations'),
        ),
        migrations.AlterField(
            model_name='habitattypeobservation',
            name='additional_info',
            field=models.CharField(blank=True, db_column='lisatieto', max_length=255, null=True, verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='habitattypeobservation',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_column='pvm_luotu', verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='habitattypeobservation',
            name='feature',
            field=models.ForeignKey(db_column='kohdeid', on_delete=django.db.models.deletion.PROTECT, related_name='habitat_type_observations', to='nature.Feature', verbose_name='feature'),
        ),
        migrations.AlterField(
            model_name='habitattypeobservation',
            name='group_fraction',
            field=models.IntegerField(blank=True, db_column='osuus_kuviosta', null=True, verbose_name='group fraction'),
        ),
        migrations.AlterField(
            model_name='habitattypeobservation',
            name='habitat_type',
            field=models.ForeignKey(db_column='ltyypid', on_delete=django.db.models.deletion.PROTECT, related_name='habitat_type_observations', to='nature.HabitatType', verbose_name='habitat type'),
        ),
        migrations.AlterField(
            model_name='habitattypeobservation',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, db_column='pvm_editoitu', null=True, verbose_name='last modified time'),
        ),
        migrations.AlterField(
            model_name='habitattypeobservation',
            name='observation_series',
            field=models.ForeignKey(db_column='hsaid', on_delete=django.db.models.deletion.PROTECT, related_name='habitat_type_observations', to='nature.ObservationSeries', verbose_name='observation series'),
        ),
        migrations.AlterField(
            model_name='habitattyperegulation',
            name='habitat_type',
            field=models.ForeignKey(db_column='ltyyppiid', on_delete=django.db.models.deletion.CASCADE, to='nature.HabitatType', verbose_name='habitat type'),
        ),
        migrations.AlterField(
            model_name='habitattyperegulation',
            name='regulation',
            field=models.ForeignKey(db_column='saadosid', on_delete=django.db.models.deletion.CASCADE, to='nature.Regulation', verbose_name='regulation'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='active',
            field=models.BooleanField(db_column='voimassa', default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='archived_time',
            field=models.DateTimeField(db_column='historia_pvm', verbose_name='archived time'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='area',
            field=models.FloatField(blank=True, db_column='pinta_ala', editable=False, null=True, verbose_name='area (ha)'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='created_by',
            field=models.CharField(blank=True, db_column='digitoija', max_length=50, null=True, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='created_time',
            field=models.DateField(auto_now_add=True, db_column='digipvm', null=True, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='description',
            field=models.CharField(blank=True, db_column='kuvaus', max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='feature',
            field=models.ForeignKey(blank=True, db_column='kohde_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_features', to='nature.Feature', verbose_name='feature'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='feature_class',
            field=models.ForeignKey(db_column='luokkatunnus', on_delete=django.db.models.deletion.PROTECT, related_name='historical_features', to='nature.FeatureClass', verbose_name='feature class'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='fid',
            field=models.CharField(blank=True, db_column='tunnus', max_length=10, null=True, verbose_name='fid'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='geometry',
            field=nature.models.PermissiveGeometryField(db_column='geometry1', srid=3879, verbose_name='geometry'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='last_modified_by',
            field=models.CharField(blank=True, db_column='muokkaaja', max_length=10, null=True, verbose_name='last modified by'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, db_column='pvm_editoitu', null=True, verbose_name='last modified time'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='name',
            field=models.CharField(blank=True, db_column='nimi', max_length=80, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='notes',
            field=models.CharField(blank=True, db_column='huom', max_length=255, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='number',
            field=models.IntegerField(blank=True, db_column='numero', null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='protection_level',
            field=models.IntegerField(choices=[(1, 'Administrators only'), (2, 'Administrators and staff'), (3, 'Public')], db_column='suojaustasoid', default=3, verbose_name='protection level'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='text',
            field=models.CharField(blank=True, db_column='teksti', max_length=40000, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='text_www',
            field=models.CharField(blank=True, db_column='teksti_www', max_length=40000, null=True, verbose_name='text www'),
        ),
        migrations.AlterField(
            model_name='linktype',
            name='name',
            field=models.CharField(blank=True, db_column='nimi', max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='migrationclass',
            name='explanation',
            field=models.CharField(blank=True, db_column='selitys', max_length=50, null=True, verbose_name='explanation'),
        ),
        migrations.AlterField(
            model_name='migrationclass',
            name='source',
            field=models.CharField(blank=True, db_column='lahde', max_length=50, null=True, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='migrationclass',
            name='value',
            field=models.IntegerField(blank=True, db_column='arvo', null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='abundance',
            field=models.ForeignKey(blank=True, db_column='runsausid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='nature.Abundance', verbose_name='abundance'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='breeding_degree',
            field=models.ForeignKey(blank=True, db_column='pesimisvarmuusid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='nature.BreedingDegree', verbose_name='breeding degree'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='code',
            field=models.CharField(blank=True, db_column='hav_koodi', max_length=100, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_column='pvm_luotu', verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='date',
            field=models.DateField(blank=True, db_column='pvm', null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='description',
            field=models.CharField(blank=True, db_column='kuvaus', max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='feature',
            field=models.ForeignKey(db_column='kohdeid', on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='nature.Feature', verbose_name='feature'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='frequency',
            field=models.ForeignKey(blank=True, db_column='yleisyysid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='nature.Frequency', verbose_name='frequence'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, db_column='pvm_editoitu', null=True, verbose_name='last modified time'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='migration_class',
            field=models.ForeignKey(blank=True, db_column='liikkumislkid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='nature.MigrationClass', verbose_name='migration class'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='notes',
            field=models.CharField(blank=True, db_column='huom', max_length=100, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='number',
            field=models.CharField(blank=True, db_column='lkm', max_length=30, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observer',
            field=models.ForeignKey(blank=True, db_column='hloid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='nature.Person', verbose_name='observer'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='occurrence',
            field=models.ForeignKey(blank=True, db_column='esiintymaid', null=True, on_delete=django.db.models.deletion.PROTECT, to='nature.Occurrence', verbose_name='occurrence'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='origin',
            field=models.ForeignKey(blank=True, db_column='alkuperaid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='nature.Origin', verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='protection_level',
            field=models.IntegerField(choices=[(1, 'Administrators only'), (2, 'Administrators and staff'), (3, 'Public')], db_column='suojaustasoid', default=3, verbose_name='protection level'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='series',
            field=models.ForeignKey(blank=True, db_column='hsaid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='nature.ObservationSeries', verbose_name='series'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='species',
            field=models.ForeignKey(db_column='lajid', on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='nature.Species', verbose_name='species'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='uri',
            field=models.URLField(blank=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='observationseries',
            name='additional_info',
            field=models.CharField(blank=True, db_column='lisatieto', max_length=255, null=True, verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='observationseries',
            name='description',
            field=models.CharField(blank=True, db_column='kuvaus', max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='observationseries',
            name='end_date',
            field=models.DateField(blank=True, db_column='loppupvm', null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='observationseries',
            name='method',
            field=models.CharField(blank=True, db_column='menetelma', max_length=255, null=True, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='observationseries',
            name='name',
            field=models.CharField(blank=True, db_column='nimi', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='observationseries',
            name='notes',
            field=models.CharField(blank=True, db_column='huomioitavaa', max_length=255, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='observationseries',
            name='person',
            field=models.ForeignKey(blank=True, db_column='hloid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_series', to='nature.Person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='observationseries',
            name='start_date',
            field=models.DateField(blank=True, db_column='alkupvm', null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='observationseries',
            name='valid',
            field=models.BooleanField(db_column='voimassa', verbose_name='valid'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='explanation',
            field=models.CharField(blank=True, db_column='selitys', max_length=50, null=True, verbose_name='explanation'),
        ),
        migrations.AlterField(
            model_name='origin',
            name='explanation',
            field=models.CharField(blank=True, db_column='selitys', max_length=50, null=True, verbose_name='explanation'),
        ),
        migrations.AlterField(
            model_name='origin',
            name='source',
            field=models.CharField(blank=True, db_column='lahde', max_length=50, null=True, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.CharField(blank=True, db_column='yritys', max_length=100, null=True, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_column='lisaysaika', null=True, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, db_column='email', max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='expertise',
            field=models.CharField(blank=True, db_column='asiantuntemus', max_length=150, null=True, verbose_name='expertise'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, db_column='etunimi', max_length=25, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.CharField(blank=True, db_column='huomioitavaa', max_length=255, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='person',
            name='public_servant',
            field=models.BooleanField(db_column='viranomainen', verbose_name='public servant'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, db_column='sukunimi', max_length=25, null=True, verbose_name='surname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone',
            field=models.CharField(blank=True, db_column='puhnro', max_length=50, null=True, verbose_name='telephone'),
        ),
        migrations.AlterField(
            model_name='protection',
            name='additional_info',
            field=models.CharField(blank=True, db_column='lisatieto', max_length=255, null=True, verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='protection',
            name='conservation_programmes',
            field=models.ManyToManyField(blank=True, related_name='protections', through='nature.ProtectionConservationProgramme', to='nature.ConservationProgramme', verbose_name='conservation programmes'),
        ),
        migrations.AlterField(
            model_name='protection',
            name='criteria',
            field=models.ManyToManyField(blank=True, related_name='protections', through='nature.ProtectionCriterion', to='nature.Criterion', verbose_name='criteria'),
        ),
        migrations.AlterField(
            model_name='protection',
            name='hiking',
            field=models.CharField(blank=True, db_column='liikkuminen', max_length=255, null=True, verbose_name='hiking'),
        ),
        migrations.AlterField(
            model_name='protection',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='protection', serialize=False, to='nature.Feature', verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='protection',
            name='land_area',
            field=models.CharField(blank=True, db_column='maapinta_ala', max_length=50, null=True, verbose_name='land area'),
        ),
        migrations.AlterField(
            model_name='protection',
            name='regulations',
            field=models.CharField(blank=True, db_column='maaraykset', max_length=255, null=True, verbose_name='regulations'),
        ),
        migrations.AlterField(
            model_name='protection',
            name='reported_area',
            field=models.CharField(blank=True, db_column='ilmoitettu_pinta_ala', max_length=50, null=True, verbose_name='reported area'),
        ),
        migrations.AlterField(
            model_name='protection',
            name='water_area',
            field=models.CharField(blank=True, db_column='vesipinta_ala', max_length=50, null=True, verbose_name='water area'),
        ),
        migrations.AlterField(
            model_name='protectionconservationprogramme',
            name='conservation_programme',
            field=models.ForeignKey(db_column='sohjelmaid', on_delete=django.db.models.deletion.CASCADE, to='nature.ConservationProgramme', verbose_name='conservation programme'),
        ),
        migrations.AlterField(
            model_name='protectionconservationprogramme',
            name='protection',
            field=models.ForeignKey(db_column='suojeluid', on_delete=django.db.models.deletion.CASCADE, to='nature.Protection', verbose_name='protection'),
        ),
        migrations.AlterField(
            model_name='protectioncriterion',
            name='criterion',
            field=models.ForeignKey(db_column='perusteid', on_delete=django.db.models.deletion.CASCADE, to='nature.Criterion', verbose_name='criterion'),
        ),
        migrations.AlterField(
            model_name='protectioncriterion',
            name='protection',
            field=models.ForeignKey(db_column='suoid', on_delete=django.db.models.deletion.CASCADE, to='nature.Protection', verbose_name='protection'),
        ),
        migrations.AlterField(
            model_name='protectionlevel',
            name='explanation',
            field=models.CharField(blank=True, db_column='selitys', max_length=50, null=True, verbose_name='explanation'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='additional_info',
            field=models.CharField(blank=True, db_column='lisatieto', max_length=255, null=True, verbose_name='additional information'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.CharField(blank=True, db_column='tekija', max_length=100, null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.CharField(blank=True, db_column='linkki', max_length=4000, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(blank=True, db_column='nimi', max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='place_of_printing',
            field=models.CharField(blank=True, db_column='painopaikka', max_length=50, null=True, verbose_name='place of printing'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.ForeignKey(db_column='julktyyppiid', on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='nature.PublicationType', verbose_name='publication type'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='series',
            field=models.CharField(blank=True, db_column='sarja', max_length=100, null=True, verbose_name='series'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.CharField(blank=True, db_column='vuosi', max_length=50, null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='publicationtype',
            name='name',
            field=models.CharField(blank=True, db_column='nimi', max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='additional_info',
            field=models.CharField(blank=True, db_column='lisatieto', max_length=255, null=True, verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='date_of_entry',
            field=models.DateTimeField(blank=True, db_column='voimaantulo', null=True, verbose_name='date of entry'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='link',
            field=models.CharField(blank=True, db_column='linkki', max_length=4000, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='name',
            field=models.CharField(blank=True, db_column='nimi', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='paragraph',
            field=models.CharField(blank=True, db_column='pykala', max_length=100, null=True, verbose_name='paragraph'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='valid',
            field=models.BooleanField(db_column='voimassa', verbose_name='valid'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='value',
            field=models.CharField(blank=True, db_column='arvo', max_length=10, null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='value_explanation',
            field=models.CharField(blank=True, db_column='arvon_selitys', max_length=255, null=True, verbose_name='value explanation'),
        ),
        migrations.AlterField(
            model_name='species',
            name='additional_info',
            field=models.CharField(blank=True, db_column='lisatieto', max_length=255, null=True, verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='species',
            name='author_1',
            field=models.CharField(blank=True, db_column='auktori1', max_length=150, null=True, verbose_name='author 1'),
        ),
        migrations.AlterField(
            model_name='species',
            name='author_2',
            field=models.CharField(blank=True, db_column='auktori2', max_length=150, null=True, verbose_name='author 2'),
        ),
        migrations.AlterField(
            model_name='species',
            name='code',
            field=models.CharField(blank=True, db_column='koodi', max_length=100, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='species',
            name='family_fi',
            field=models.CharField(blank=True, db_column='heimo_suomi', max_length=150, null=True, verbose_name='family (fi)'),
        ),
        migrations.AlterField(
            model_name='species',
            name='family_la',
            field=models.CharField(blank=True, db_column='heimo_tiet', max_length=150, null=True, verbose_name='family (la)'),
        ),
        migrations.AlterField(
            model_name='species',
            name='link',
            field=models.CharField(blank=True, db_column='linkki', max_length=4000, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_abbreviated_1',
            field=models.CharField(blank=True, db_column='nimilyhenne1', max_length=10, null=True, verbose_name='name abbreviated 1'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_abbreviated_2',
            field=models.CharField(blank=True, db_column='nimilyhenne2', max_length=10, null=True, verbose_name='name abbreviated 2'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_en',
            field=models.CharField(blank=True, db_column='nimi_englanti', max_length=150, null=True, verbose_name='name (en)'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_fi',
            field=models.CharField(blank=True, db_column='nimi_suomi1', max_length=150, null=True, verbose_name='name (fi)'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_fi_2',
            field=models.CharField(blank=True, db_column='nimi_suomi2', max_length=150, null=True, verbose_name='name 2 (fi)'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_sci_1',
            field=models.CharField(blank=True, db_column='nimi_tiet1', max_length=150, null=True, verbose_name='scientific name 1'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_sci_2',
            field=models.CharField(blank=True, db_column='nimi_tiet2', max_length=150, null=True, verbose_name='scientific name 2'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_subspecies_1',
            field=models.CharField(blank=True, db_column='alalaji1', max_length=150, null=True, verbose_name='subspecies 1'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_subspecies_2',
            field=models.CharField(blank=True, db_column='alalaji2', max_length=150, null=True, verbose_name='subscecies 2'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_sv',
            field=models.CharField(blank=True, db_column='nimi_ruotsi', max_length=150, null=True, verbose_name='name (sv)'),
        ),
        migrations.AlterField(
            model_name='species',
            name='order_fi',
            field=models.CharField(blank=True, db_column='lahko_suomi', max_length=150, null=True, verbose_name='order (fi)'),
        ),
        migrations.AlterField(
            model_name='species',
            name='order_la',
            field=models.CharField(blank=True, db_column='lahko_tiet', max_length=150, null=True, verbose_name='order (la)'),
        ),
        migrations.AlterField(
            model_name='species',
            name='protection_level',
            field=models.IntegerField(choices=[(1, 'Administrators only'), (2, 'Administrators and staff'), (3, 'Public')], db_column='suojaustasoid', default=3, verbose_name='protection level'),
        ),
        migrations.AlterField(
            model_name='species',
            name='registry_date',
            field=models.DateTimeField(blank=True, db_column='rekisteripvm', null=True, verbose_name='registry date'),
        ),
        migrations.AlterField(
            model_name='species',
            name='regulations',
            field=models.ManyToManyField(related_name='species', through='nature.SpeciesRegulation', to='nature.Regulation', verbose_name='regulations'),
        ),
        migrations.AlterField(
            model_name='species',
            name='taxon',
            field=models.CharField(blank=True, db_column='ryhma', max_length=5, null=True, verbose_name='taxon'),
        ),
        migrations.AlterField(
            model_name='species',
            name='taxon_1',
            field=models.CharField(blank=True, db_column='elioryhma1', max_length=50, null=True, verbose_name='taxon 1'),
        ),
        migrations.AlterField(
            model_name='species',
            name='taxon_2',
            field=models.CharField(blank=True, db_column='elioryhma2', max_length=50, null=True, verbose_name='taxon 2'),
        ),
        migrations.AlterField(
            model_name='speciesregulation',
            name='regulation',
            field=models.ForeignKey(db_column='saaid', on_delete=django.db.models.deletion.CASCADE, to='nature.Regulation', verbose_name='regulation'),
        ),
        migrations.AlterField(
            model_name='speciesregulation',
            name='species',
            field=models.ForeignKey(db_column='lajid', on_delete=django.db.models.deletion.CASCADE, to='nature.Species', verbose_name='species'),
        ),
        migrations.AlterField(
            model_name='square',
            name='additional_info',
            field=models.CharField(blank=True, db_column='lisatieto', max_length=255, null=True, verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='square',
            name='degree_of_determination',
            field=models.IntegerField(blank=True, db_column='selvitysaste', null=True, verbose_name='degree of determination'),
        ),
        migrations.AlterField(
            model_name='square',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='square', serialize=False, to='nature.Feature', verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='square',
            name='number',
            field=models.CharField(blank=True, db_column='nro', max_length=10, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, db_column='pvm', null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, db_column='kuvaus', max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='features',
            field=models.ManyToManyField(related_name='transactions', through='nature.TransactionFeature', to='nature.Feature', verbose_name='features'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_modified_by',
            field=models.CharField(blank=True, db_column='paivittaja', max_length=20, null=True, verbose_name='last modified by'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='link',
            field=models.CharField(blank=True, db_column='linkki', max_length=4000, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='person',
            field=models.ForeignKey(blank=True, db_column='hloid', null=True, on_delete=django.db.models.deletion.PROTECT, to='nature.Person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='protection_level',
            field=models.IntegerField(choices=[(1, 'Administrators only'), (2, 'Administrators and staff'), (3, 'Public')], db_column='suojaustasoid', default=3, verbose_name='protection level'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='register_id',
            field=models.CharField(blank=True, db_column='diaarinro', max_length=20, null=True, verbose_name='register id'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='regulations',
            field=models.ManyToManyField(related_name='transactions', through='nature.TransactionRegulation', to='nature.Regulation', verbose_name='regulations'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(related_name='transactions', db_column='tapahtumatyyppiid', on_delete=django.db.models.deletion.PROTECT, to='nature.TransactionType', verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='transactionfeature',
            name='feature',
            field=models.ForeignKey(db_column='kohdeid', on_delete=django.db.models.deletion.CASCADE, to='nature.Feature', verbose_name='feature'),
        ),
        migrations.AlterField(
            model_name='transactionfeature',
            name='transaction',
            field=models.ForeignKey(db_column='tapid', on_delete=django.db.models.deletion.CASCADE, to='nature.Transaction', verbose_name='transaction'),
        ),
        migrations.AlterField(
            model_name='transactionregulation',
            name='regulation',
            field=models.ForeignKey(db_column='saaid', on_delete=django.db.models.deletion.CASCADE, to='nature.Regulation', verbose_name='regulation'),
        ),
        migrations.AlterField(
            model_name='transactionregulation',
            name='transaction',
            field=models.ForeignKey(db_column='tapid', on_delete=django.db.models.deletion.CASCADE, to='nature.Transaction', verbose_name='transaction'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(blank=True, db_column='nimi', max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='value',
            name='date',
            field=models.DateField(blank=True, db_column='pvm', null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='value',
            name='explanation',
            field=models.CharField(blank=True, db_column='selite', max_length=50, null=True, verbose_name='explanation'),
        ),
        migrations.AlterField(
            model_name='value',
            name='link',
            field=models.CharField(blank=True, db_column='linkki', max_length=4000, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='value',
            name='valuator',
            field=models.CharField(blank=True, db_column='arvottaja', max_length=50, null=True, verbose_name='valuator'),
        ),
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.CharField(blank=True, db_column='luokka', max_length=10, null=True, verbose_name='value class'),
        ),
    ]
