# Generated by Django 2.0 on 2018-12-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nature", "0008_extend_last_modified_by_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="protection_level",
            field=models.IntegerField(
                choices=[(1, "Admin"), (3, "Office"), (2, "Office Hki"), (4, "Public")],
                db_column="suojaustasoid",
                default=4,
                verbose_name="protection level",
            ),
        ),
        migrations.AlterField(
            model_name="featurelink",
            name="protection_level",
            field=models.IntegerField(
                choices=[(1, "Admin"), (3, "Office"), (2, "Office Hki"), (4, "Public")],
                db_column="suojaustasoid",
                default=4,
                verbose_name="protection level",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfeature",
            name="protection_level",
            field=models.IntegerField(
                choices=[(1, "Admin"), (3, "Office"), (2, "Office Hki"), (4, "Public")],
                db_column="suojaustasoid",
                default=4,
                verbose_name="protection level",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="protection_level",
            field=models.IntegerField(
                choices=[(1, "Admin"), (3, "Office"), (2, "Office Hki"), (4, "Public")],
                db_column="suojaustasoid",
                default=4,
                verbose_name="protection level",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="protection_level",
            field=models.IntegerField(
                choices=[(1, "Admin"), (3, "Office"), (2, "Office Hki"), (4, "Public")],
                db_column="suojaustasoid",
                default=4,
                verbose_name="protection level",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="protection_level",
            field=models.IntegerField(
                choices=[(1, "Admin"), (3, "Office"), (2, "Office Hki"), (4, "Public")],
                db_column="suojaustasoid",
                default=4,
                verbose_name="protection level",
            ),
        ),
    ]
