# Generated by Django 2.1.5 on 2019-01-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nature", "0010_remove_office_hki_protection_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="observation",
            old_name="number",
            new_name="quantity",
        ),
    ]
