# Generated by Django 2.2.16 on 2020-10-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nature", "0017_expand_person_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publication",
            options={
                "ordering": ("-year",),
                "verbose_name": "publication",
                "verbose_name_plural": "publications",
            },
        ),
    ]
