# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='created_by',
            new_name='uploaded_by',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='created_time',
            new_name='uploaded_time',
        ),
    ]
