# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_rename_file_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='uploaded time'),
        ),
    ]
