# Generated by Django 2.2.16 on 2020-11-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HMACGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="group name")),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("office_hki", "Office HKI"),
                            ("office", "Office"),
                        ],
                        default="office",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
